<a href="https://colab.research.google.com/github/eduardmendoza92/datawarehouse-seguros/blob/main/notebooks/Aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/eduardmendoza92/datawarehouse-seguros/refs/heads/main/data/aseguradoras.csv

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/eduardmendoza92/datawarehouse-seguros/refs/heads/main/data/aseguradoras.csv"

df = pd.read_csv(url)

df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [ ]:
#Exploracion de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [ ]:
#Limpieza de datos
aseguradoras=df.copy()
print(aseguradoras['pais'].value_counts(dropna=False))

pais
El Salvador    3
ElSalvador     3
Costa Rica     2
NaN            2
Panamá         2
Honduras       2
Guatemala      1
Name: count, dtype: int64

In [ ]:
aseguradoras['pais'] = aseguradoras['pais'].replace('ElSalvador', 'El Salvador')
print(aseguradoras['pais'].value_counts(dropna=False))

pais
El Salvador    6
Costa Rica     2
NaN            2
Panamá         2
Honduras       2
Guatemala      1
Name: count, dtype: int64

In [ ]:
asegudoras=df.copy()
print(aseguradoras['rating_riesgo'].value_counts(dropna=False))

rating_riesgo
Alto     4
Bajo     4
NaN      3
Medio    2
B        1
D        1
Name: count, dtype: int64

In [ ]:
#Separar datos válidos y rechazados
validos = aseguradoras[
    aseguradoras['pais'].notna() &
    aseguradoras['rating_riesgo'].notna()
].copy()

rechazados = asegudoras[asegudoras['pais'].isna() |
aseguradoras['rating_riesgo'].isna()
].copy()

In [ ]:
#Motivo de rechazo
def motivo(row):
    motivos = []
    if pd.isna(row['pais']):
        motivos.append("pais_vacio")
    if pd.isna(row['rating_riesgo']):
        motivos.append("rating_riesgo_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [ ]:
validos.to_csv("aseguradoras_curated.csv", index=False)

rechazados.to_csv("aseguradoras_rejects.csv", index=False)